name: football-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0  # For data manipulation
  - numpy>=1.24  # For numerical computations
  - matplotlib>=3.7  # For plotting
  - seaborn>=0.12  # For advanced visualizations
  - scikit-learn>=1.2  # For machine learning models and preprocessing
  - imbalanced-learn>=0.10  # For handling class imbalance (SMOTE)
  - requests>=2.31  # For API calls
  - python-dateutil>=2.8  # For date parsing
  - pytz>=2023.3  # For timezone handling
  - jupyter>=1.0  # For running notebooks
  - ipykernel>=6.0  # Jupyter kernel
  - tqdm>=4.65  # For progress bars
  - pyyaml>=6.0  # For YAML file handling
  - pip>=23.0
  - pip:
      - python-dotenv>=1.0  # For loading environment variables
      - loguru>=0.7  # Alternative to logging
      - beautifulsoup4>=4.12  # HTML parsing
      - lxml>=4.9  # XML parsing
      - joblib>=1.3  # For parallel processing
      - scikit-plot>=0.3  # For additional plotting utilities
      - xgboost>=1.7  # For advanced machine learning models
      - pytest>=7.0  # For testing
      - mypy>=1.0  # For type checking
      - black>=23.0  # For code formatting
      - flake8>=6.0  # For linting
